export HADOOP_COMMON_HOME="/usr/lib/hadoop/"
export HADOOP_CONF_DIR="/etc/hadoop/conf"
export HADOOP_HDFS_HOME="/usr/lib/hadoop-hdfs"
export HADOOP_MAPRED_HOME="/usr/lib/hadoop-mapreduce"
export HADOOP_YARN_HOME="/usr/lib/hadoop-yarn/"
