
redis:
  image: redis:2.8

postgres:
  image: postgres:9.3
  environment:
    POSTGRES_PASSWORD: "postgres"

sentry:
  build: ./
  links:
    - redis
    - postgres
  ports:
    - "9000:9000"
  environment:
    SECRET_KEY: secret
    SENTRY_URL_PREFIX: http://192.168.99.100:9000
    SENTRY_DB_PASSWORD: postgres
